config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    resources :images, only: :create
    resources :comments, only: :create 
    collection do
      get 'search'
    end
  end
  resources :users, only: :index do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, :text, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :post, optional: true

  mount_uploader :image, ImageUploader
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :post, optional: true

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :parts, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  accepts_nested_attributes_for :parts, allow_destroy: true

  validates :title, :text, presence: true
end

app/models/type.rb
class Type < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :posts
  has_many :parts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create(comment_params)
    @post = @comment.post
    @comment.save
    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  def index
    @post = Post.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :move_to_index, except: [:index, :show]
  before_action :set_find,only:[:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order("created_at DESC").page(params[:page]).per(4)
  end

  def new
    @post = Post.new
    @post.images.build
    @post.parts.build
  end
  
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else 
      flash[:alert] = "入力してください"
      render "new"
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)    
  end

  def edit

  end
  
  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to root_path(post.id)
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, images_attributes: [:image], parts_attributes: [:name]).merge(user_id: current_user.id)
  end

  def set_find
    @post = Post.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.find(current_user[:id])
    @posts = @user.posts
    # @nickname = @user.nickname
    # @posts = @user.post.page(params[:page]).per(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IndividualApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_footer.html.haml
.footer
.child
  .child__box 「筋肉好きよ集まれ💪」が皆さんの役に立ちますように
.grandchild
  .grandchild__box ©︎ KINNIKU muscle.

app/views/posts/_header.html.haml
- if user_signed_in?
  = render "login_header"
- else
  = render "no_login_header"

app/views/posts/_login_header.html.haml
.login
  .login__box 
    = link_to "筋肉好きよ集まれ💪", root_path
    .login__box__main
      .login__box__main--left
        = link_to "新規投稿", new_post_path
      .login__box__main--center
        = link_to users_path do
          = current_user.nickname
      .login__box__main--right
        = link_to "ログアウト", destroy_user_session_path, method: :delete

app/views/posts/_no_login_header.html.haml
.nologin
  .nologin__box 
    = link_to "筋肉好きよ集まれ💪", root_path
    .nologin__box__main
      .nologin__box__main--left
        = link_to "ログイン", new_user_session_path
      .nologin__box__main--right
        = link_to "新規登録", new_user_registration_path

app/views/posts/edit.html.haml
= render "login_header"
.edit 
  .edit__box 
    投稿の編集
  = form_for @post,html: { class: "edit__box-big" } do |f|
    = f.text_field :title, class: 'edit__box-big-title', placeholder: "タイトル"
    = f.text_area :text, class: 'edit__box-big-area', placeholder: "ブログの本文", rows: 10
    = f.submit '編集完了', class: 'edit__box-big-submit' 

app/views/posts/index.html.haml
= render 'header'
.main
  .main__toko
    投稿一覧
  - @posts.each do |post|
    = link_to post_path "#{post.id}", class: "main__show" do
      .main__stripe
      .main__text
        .main__text__image 
          - if post.images.present?
            = image_tag post.images.first.image.url(:medium)
          - else 
            %img{src: "https://i.gyazo.com/2b858b92bc7766cd610947f90a935b6d.png"}/
        .main__text__title 
          .main__text__title__box
            = link_to post.title, post_path(post.id)
          .main__text__title__part
            部位
            = post.parts.first.name 
          .main__text__title__text
          .main__text__title__name
            = post.user.nickname
            = post.created_at 
.page 
  = paginate(@posts)
= render 'footer'

app/views/posts/new.html.haml
= render "login_header"
.new 
  .new__box 
    新規投稿の作成
  = form_for @post do |f|
    .new__box-big--image
      = f.fields_for :images do |i|
        .new__box-big--text 
          = icon("fa", "camera")
          = i.file_field :image, id: :user_image
    .new__box-big--part
      = f.fields_for :parts do |i|
        = i.select :name,[["腕","腕"],["脚","脚"],["肩","肩"],["背中","背中"],["お尻","お尻"],["腹筋","腹筋"],["全身","全身"],["その他","その他"]]   
    = f.text_field :title, class: 'new__box-big-title', placeholder: "タイトル"
    = f.text_area :text, class: 'new__box-big-area', placeholder: "ブログの本文", rows: 10
    = f.submit '投稿する', class: 'new__box-big-submit' 

app/views/posts/show.html.haml
= render "header"
.show
  .show__stripe
  .show__text
    .show__text__image 
      - if @post.images.present?
        = image_tag @post.images.first.image.url(:medium)
    .show__text__title 
      .show__text__title__box
        = @post.title
      .show__text__title__part
        部位
        = @post.parts.first.name
      .show__text__title__name
        = @post.user.nickname
        = @post.created_at
  .show__edit
    - if user_signed_in? && current_user.id == @post.user_id
      .show__edit--edit
        = link_to '編集', edit_post_path(@post.id)
      .show__edit--des
        = link_to '削除', post_path(@post.id), method: :delete
        -# .show__edit--des--space
    - else 
      .show__edit--box
  .show__content 
    = simple_format @post.text
.box
  .comment__comments
    - if @comments
      - @comments.each do |comment|
        .comment__box
          .comment__box--name
            = link_to comment.user.nickname
          .comment__box--comment
            = comment.text
  .comment
    .comment__caution
      相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは相手の事を不愉快にしてしまう事があります。そのような言葉は控えてください。
    - if user_signed_in? 
      = form_for [@post, @comment] do |f| 
        = f.text_area :text, class: 'comment__area', placeholder: "コメント", rows: "5"
        = f.submit "コメントする", class: 'comment__submit' 

app/views/users/index.html.haml
= render '/posts/login_header'
.userindex
  - @posts.each do |post|
    .userindex__stripe
    .userindex__text
      .userindex__text__image
        - if post.images.present?
          = image_tag post.images.first.image.url(:medium)
      .userindex__text__title 
        .userindex__text__title__box
          = post.title
        .userindex__text__title__name
          = post.user.nickname
          = post.created_at
        .userindex__text__title__text
    .show__edit
      .show__edit--edit
        = link_to '編集', edit_post_path(post.id)
      .show__edit--des
        = link_to '削除', post_path(post.id), method: :delete
    .userindex__content 
      = simple_format post.text



-# .main
-#   .main__toko
-#     投稿一覧
-#   - @posts.each do |post|
-#     = link_to post_path "#{post.id}", class: "main__show" do
-#       .main__stripe
-#       .main__text
-#         .main__text__image 
-#           = image_tag @post.images.first.image.url(:medium)
-#         .main__text__title 
-#           .main__text__title__box
-#             = link_to @post.title, post_path(post.id)
-#           .main__text__title__text
-#           .main__text__title__name
-#             = @post.user.nickname
-#             = @post.created_at
-# .page 
  -# = paginate(@posts)
-# = render '/posts/footer'